### PR TITLE
Merge: cm12.1 to cancro-kk-oss

### PR DESCRIPTION
**Pull request by ajitkatte**

### CODE REVIEW

**Comment by ivan19871002** [comment]
I create a new branch lollipop-mr1 ,  that is can be used

**Comment by ajitkatte** [comment]
Yes, I created merge request for wrong branch.

**Comment by PepeII** [comment]
Which version GCC and Cross Compiler Toolchain do you use? I am not able to compile your kernel with GCC 4.9 and Linaro 4.9.3

**Comment by ajitkatte** [comment]
I'm using Linaro 4.9.3 and I am able to compile the kernel souces
flawlessly.

**Pull request closed without merging**
